[build-system]
requires = ["hatchling>=1.18"]
build-backend = "hatchling.build"

[project]
name = "weco-extract-line-plot"
version = "0.0.0"
description = "Local uv env for running prepare_data.py"
requires-python = ">=3.9"
dependencies = [
    "huggingface_hub",
    "openai>=1.0.0",
]

[tool.uv]
package = false


