name: Lint and Format Code

on:
  push:
    branches:
      - main
      - dev
  pull_request:  # Run on any pull request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.0"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Run Linter (Check Only)
      run: |
        ruff check .
        ruff format --check .
